- name: Set HostName
  ansible.builtin.shell: set-hostname {{env}}-{{component}}

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: copy the expense config file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import role app-prereq from common
  ansible.builtin.import_role:
     name: common
     tasks_from: app-prereq
  vars:
    app_dir : /usr/share/nginx/html
    component: frontend
    app_user: root

- name: Reload service nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded
    enabled: true

- name: Import elk
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: Import prometheus node-exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter

#- name: Install new relic agent
 # ansible.builtin.shell: curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo NEW_RELIC_API_KEY="{{ lookup('amazon.aws.aws_ssm', 'NEW_RELIC_API_KEY', region='us-east-1' ) }}" NEW_RELIC_ACCOUNT_ID=4368081 NEW_RELIC_REGION=US /usr/local/bin/newrelic install -n nginx-open-source-integration --tag {{component}}

- name: Install newrelic nginx agent
  ansible.builtin.dnf:
    name: nri-nginx
    status: installed

- name: copy the nginx newrelic conf file
  ansible.builtin.template:
    src: nr-nginx
    dest: /etc/newrelic-infra/integrations.d/nginx-config.yml

- name: copy the nginx newrelic log shipper file
  ansible.builtin.template:
    src: nr-nginx-log
    dest: /etc/newrelic-infra/logging.d/nginx-log.yml

##