groups:
  - name: {{component}}-{{env}}
    rules:
      - alert: NginxServiceMonitor
        expr: node_systemd_unit_state{name="nginx.service",state="active"} == 0
        for: 1m
        labels:
          severity: critical
          component: {{component}}
          env: {{env}}
        annotations:
          summary: Critical | Frontend Nginx Service Down

